openapi: 3.0.0
servers:
  - url: 'https://virtserver.swaggerhub.com/zerox/nettaton/1.0.0'
info:
  version: "1.0.0-oas3"
  title: Nettaton
  description: >-
    API used to store game score for registerd users
paths:
  /users:
    post:
      summary: Create a new user
      description: How users can signup to nettaton
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/users'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_user''
        description: user to register
        required: true
    get:
      summary: List all scores
      description: This operation will return a list of all scores
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                users:
                  type: array
                  $ref: '#/components/schemas/users'
  /scores:
    get:
      summary: List all scores
      description: This operation will return a list of all scores
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/scores'
components:
  schemas:
    create_user:
      required:
        - username
        - passowrd
        - email
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
      type: object
    user:
      type: object
      properties:
        _id:
          type: string
          description: The users ID.
        username:
          type: string
          description: The username.
        email:
          type: string
          description: The users email.
    scores:
      properties:
        scores:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              userAnwser:
                type: string
              actualAnwser:
                type: string
              correct:
                type: boolean